# -*- coding: utf-8 -*-
"""lotka_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pRNXQHfnGRDURpSiG7ADaXfZMq-wByUY
"""

codigo = '''
import numpy as np
import matplotlib.pyplot as plt
import streamlit as st

# === Función de simulación del modelo ===
def simulate_lv(alpha, beta, gamma, delta, sigma=0.0, T=50, dt=0.01):
    N = int(T / dt)
    t = np.linspace(0, T, N)
    x = np.zeros(N); y = np.zeros(N)
    x[0] = 10; y[0] = 5
    for i in range(1, N):
        dx = (alpha * x[i-1] - beta * x[i-1] * y[i-1]) * dt + sigma * np.sqrt(dt) * np.random.randn()
        dy = (delta * x[i-1] * y[i-1] - gamma * y[i-1]) * dt + sigma * np.sqrt(dt) * np.random.randn()
        x[i] = max(x[i-1] + dx, 0)
        y[i] = max(y[i-1] + dy, 0)
    return t, x, y

# === Interfaz de Streamlit ===
st.title("Simulación interactiva: Modelo Lotka-Volterra Estocástico")

# Deslizadores
alpha = st.slider('Tasa de crecimiento de presas (α)', 0.1, 2.0, 1.1, 0.1)
beta  = st.slider('Tasa de depredación (β)', 0.0, 1.0, 0.4, 0.05)
gamma = st.slider('Tasa de mortalidad de depredadores (γ)', 0.1, 2.0, 0.4, 0.1)
delta = st.slider('Tasa de conversión (δ)', 0.0, 1.0, 0.1, 0.05)
sigma = st.slider('Nivel de ruido (σ)', 0.0, 1.0, 0.2, 0.05)

# Simulación
t, x, y = simulate_lv(alpha, beta, gamma, delta, sigma)

# === Gráfico 1: Evolución temporal ===
st.subheader("Evolución temporal")
fig1, ax1 = plt.subplots()
ax1.plot(t, x, label="Presas", color="blue")
ax1.plot(t, y, label="Depredadores", color="red")
ax1.set_xlabel("Tiempo")
ax1.set_ylabel("Población")
ax1.legend()
st.pyplot(fig1)

# === Gráfico 2: Retrato de fase ===
st.subheader("Retrato de fase (presas vs depredadores)")
fig2, ax2 = plt.subplots()
ax2.plot(x, y, color="purple")
ax2.set_xlabel("Presas")
ax2.set_ylabel("Depredadores")
st.pyplot(fig2)

# === Gráfico 3: Histograma final ===
st.subheader("Distribución final")
fig3, ax3 = plt.subplots()
ax3.hist(x[-100:], bins=20, alpha=0.5, label="Presas")
ax3.hist(y[-100:], bins=20, alpha=0.5, label="Depredadores")
ax3.set_title("Distribución en los últimos pasos")
ax3.legend()
st.pyplot(fig3)
'''

with open("lotka_app.py", "w") as f:
    f.write(codigo)